{
 "title": "Minio cluster metrics VNPTIT",
 "description": "https://min.io/ is  High Performance Object Storage Amazon S3 compatible. This dashboard\r\ncollect all actual monitoring stats for minio cluster 2020-01-03T20-33-14Z version\r\n",
 "tags": [
  "object-storage",
  "OS",
  "percona"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "minIO cluster",
    "query": "label_values({__name__=~\"minio_disks_total\"}, instance)"
   },
   {
    "name": "disks",
    "query": "label_values({__name__=~\"disk_storage_available\"}, disk)"
   },
   {
    "name": "seconds",
    "query": "label_values({__name__=\"s3_ttfb_seconds_bucket\"}, le)"
   },
   {
    "name": "version",
    "query": "label_values({__name__=\"minio_version_info\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the Minio server",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "Disks total per host",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minio_disks_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Disks offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minio_disks_offline {instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Storage Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_total{disk=\"$disks\",instance=\"$host\"}",
     "legendFormat": "Available Storage: "
    }
   ]
  },
  {
   "title": "Disk Storage Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_available{disk=\"$disks\",instance=\"$host\"}",
     "legendFormat": "Available Storage: "
    }
   ]
  },
  {
   "title": "Disk Storage Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used{disk=\"$disks\",instance=\"$host\"}",
     "legendFormat": "Used Storage:"
    }
   ]
  },
  {
   "title": "Current http read rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{api=~\"get.*|list.*|head.*\", instance=\"$host\"})",
     "legendFormat": "$host get+list+head"
    }
   ]
  },
  {
   "title": "Current http write rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{api=~\"put.*\", instance=\"$host\"})",
     "legendFormat": "$host put "
    }
   ]
  },
  {
   "title": "Current http delete rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{api=~\"delete.*\", instance=\"$host\"})",
     "legendFormat": "$host delete "
    }
   ]
  },
  {
   "title": "Current  read requests less then $seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_ttfb_seconds_bucket{api=~\"get.*|list.*|head.*\", instance=\"$host\",le=\"$seconds\"})",
     "legendFormat": "Total  get+list+head le $seconds"
    }
   ]
  },
  {
   "title": "Current  write requests  less then $seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_ttfb_seconds_bucket{api=~\"get.*|list.*|head.*\", instance=\"$host\",le=\"$seconds\"})",
     "legendFormat": "Total  get+list+head le $seconds"
    }
   ]
  },
  {
   "title": "Current  delete requests less then $seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_ttfb_seconds_bucket{api=~\"delete.*\", instance=\"$host\",le=\"$seconds\"})",
     "legendFormat": "Total  get+list+head le $seconds"
    }
   ]
  },
  {
   "title": "Total request",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "s3_requests_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Errors count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "s3_errors_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(internode_rx_bytes_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Inbound "
    },
    {
     "expr": "sum(rate(internode_tx_bytes_total{instance=\"$host\"}[5m]))",
     "legendFormat": "Outgoing "
    }
   ]
  }
 ]
}